server:
  port: 8081

spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 320923
  redis:
    host: localhost
    port: 6379
    password: ""
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 127.0.0.1 # IP地址
    port: 5672 # 端口号
    username: hmdianping # 用户名
    password: 123456 # 密码
    virtual-host: /hmdianping
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
        acknowledge-mode: manual
        prefetch: 1
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false

mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包

logging:
  level:
    com.hmdp: debug

hmdp:
  jwt:
    #    # 设置jwt签名加密时使用的秘钥
    #    admin-secret-key: itcast
    #    # 设置jwt过期时间
    #    admin-ttl: 7200000
    #    # 设置前端传递过来的令牌名称
    #    admin-token-name: token
    user-secret-key: ThisIsA32BytesLongSecretKeyForHS256
    user-ttl: 7200000
    user-token-name: authorization
