server:
  port: 8090

spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    mcp:
      client:
        request-timeout: 360s
        stdio:
          servers-configuration: classpath:/config/mcp-servers-config.json
    openai:
      base-url: https://pro-share-aws-api.zcyai.com/
      api-key: sk-b1dNTAXqTai1n9kP19517d7820C2427
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://localhost:11434
      mode: embed  # 补充嵌入模式（根据项目要求填写，不能为空）
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

logging:
  level:
    root: info
  config: classpath:logback-spring.xml